//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.GA.BE.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Usuario
    {
        [DataMember]
        public int Id_Usuario { get; set; }
        [DataMember]
        public string Nombres { get; set; }
        [DataMember]
        public string Apellidos { get; set; }
        [DataMember]
        public string Usuario1 { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string UsuarioCreacion { get; set; }
        [DataMember]
        public System.DateTime FechaCreacion { get; set; }
        [DataMember]
        public string UsuarioModificacion { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        [DataMember]
        public int Id_Puesto { get; set; }
        [DataMember]
        public string Estado { get; set; }
        [DataMember]
        public virtual Puesto Puesto { get; set; }
    }
}
