//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.GA.TEST.ProxyUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuario.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/DoWork", ReplyAction="http://tempuri.org/IServiceUsuario/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/DoWork", ReplyAction="http://tempuri.org/IServiceUsuario/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/UsuarioValidarLogin", ReplyAction="http://tempuri.org/IServiceUsuario/UsuarioValidarLoginResponse")]
        MD.GA.COMMOM.Response.Response<MD.GA.BE.Entidades.Usuario> UsuarioValidarLogin(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/UsuarioValidarLogin", ReplyAction="http://tempuri.org/IServiceUsuario/UsuarioValidarLoginResponse")]
        System.Threading.Tasks.Task<MD.GA.COMMOM.Response.Response<MD.GA.BE.Entidades.Usuario>> UsuarioValidarLoginAsync(string usuario, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : MD.GA.TEST.ProxyUsuario.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<MD.GA.TEST.ProxyUsuario.IServiceUsuario>, MD.GA.TEST.ProxyUsuario.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public MD.GA.COMMOM.Response.Response<MD.GA.BE.Entidades.Usuario> UsuarioValidarLogin(string usuario, string password) {
            return base.Channel.UsuarioValidarLogin(usuario, password);
        }
        
        public System.Threading.Tasks.Task<MD.GA.COMMOM.Response.Response<MD.GA.BE.Entidades.Usuario>> UsuarioValidarLoginAsync(string usuario, string password) {
            return base.Channel.UsuarioValidarLoginAsync(usuario, password);
        }
    }
}
